### ISSUE TITLE
GLM.jl tutorial: missing `stderror` for LinearRegressor()

### ISSUE THREAD

**Issue by gd1989** [JuliaAI/DataScienceTutorials.jl#116]
The current version of the tutorial tries to access the standard error of the fitted parameters. However, no such field exists.

```julia
k = collect(keys(fp.fitted_params_given_machine))[3]
...
println("\n Standard Error per Coefficient \n",
        r.report_given_machine[k].stderror)
```

**Comment by tlienart** [comment]
it's a function exported by GLM (still is) so it should be fine to do `stderror(coefficient)` 

@drcxcruz would you mind having a look? thanks!

**Comment by ablaom** [comment]
@gd1989 The `stderror` is not part of `fitted_params(mach)`; it is part of  `report(mach)`. Since `stderror` is not used to make predictions it is not considered a learned parameter. 

By the way, the new way to access nested reports will not work with GLM until GLM releases a patch for this PR https://github.com/JuliaStats/GLM.jl/pull/378 .

**Comment by drcxcruz** [comment]
hello,

I plan to revisit the GLM tutorial to ensure they work in the latest
version of MLJ 0.20.  I'm just waiting a bit to ensure we clear out any
0.20 bugs, if any :)   It is not clear when the GLM team will release our
PR, however.

Let me know if  you need any help upgrading the other tutorial to MLJ 0.20.

Thanks

**Comment by ablaom** [comment]
@gd1989 Thanks for that! Perhaps if you also nag GLM, that will help :smile

**Comment by ablaom** [comment]
Just nagged GLM again.

**Comment by ablaom** [comment]
@drcxcruz GLM has tagged a new release with the fix. Let me know if that resolves the issue you were having. (I couldn't find an open issue about it)

**Comment by drcxcruz** [comment]
hello,

I am happy to say the GLM fix has resolved the MLJ issue.   We need to change  the following jupyter notebook cells in the tutorial https://alan-turing-institute.github.io/DataScienceTutorials.jl/end-to-end/glm/.   I know tutorials are not easy to modify or change via github.    can @tlienart change the tutorial? :)



> **_LinearModel_**
> ####OLD CELL
> 
> ŷ = MLJ.predict(LinearModel, X)
> yhatResponse = [ŷ[i,1].μ for i in 1:nrow(y)]
> residuals = y .- yhatResponse
> r = report(LinearModel)
> 
> k = collect(keys(fp.fitted_params_given_machine))[3]
> println("\n Coefficients:  ", fp.fitted_params_given_machine[k].coef)
> println("\n y \n ", y[1:5,1])
> println("\n ŷ \n ", ŷ[1:5])
> println("\n yhatResponse \n ", yhatResponse[1:5])
> println("\n Residuals \n ", y[1:5,1] .- yhatResponse[1:5])
> println("\n Standard Error per Coefficient \n", r.report_given_machine[k].stderror)
> 
> 
> ####NEW CELL REPLACEMENT
> ŷ = MLJ.predict(LinearModel, X)
> yhatResponse = [ŷ[i,1].μ for i in 1:nrow(y)]
> residuals = y .- yhatResponse
> r = report(LinearModel)
> 
> println("\n Coefficients:  ", fitted_params(LinearModel).linear_regressor.coef)
> println("\n y \n ", y[1:5,1])
> println("\n ŷ \n ", ŷ[1:5])
> println("\n yhatResponse \n ", yhatResponse[1:5])
> println("\n Residuals \n ", y[1:5,1] .- yhatResponse[1:5])
> println("\n Standard Error per Coefficient \n", r.linear_regressor.stderror[2:end])
> 

##############################

> **_LogisticModel_**
> ####OLD CELL
>  
> ŷ = MLJ.predict(LogisticModel, X)
> residuals = [1 - pdf(ŷ[i], y[i,1]) for i in 1:nrow(y)]
> r = report(LogisticModel)
> 
> k = collect(keys(fp.fitted_params_given_machine))[3]
> println("\n Coefficients:  ", fp.fitted_params_given_machine[k].coef)
> println("\n y \n ", y[1:5,1])
> println("\n ŷ \n ", ŷ[1:5])
> println("\n residuals \n ", residuals[1:5])
> println("\n Standard Error per Coefficient \n", r.report_given_machine[k].stderror)
> 
> 
> ####NEW CELL REPLACEMENT
> 
> ŷ = MLJ.predict(LogisticModel, X)
> residuals = [1 - pdf(ŷ[i], y[i,1]) for i in 1:nrow(y)]
> r = report(LogisticModel)
> 
> println("\n Coefficients:  ", fitted_params(LogisticModel).linear_binary_classifier.coef)
> println("\n y \n ", y[1:5,1])
> println("\n ŷ \n ", ŷ[1:5])
> println("\n residuals \n ", residuals[1:5])
> println("\n Standard Error per Coefficient \n", r.linear_binary_classifier.stderror[2:end])
> 
>

**Comment by ablaom** [comment]
@drcxcruz Are you able to make a PR where you make the changes directly on the (Literate.jl-compatible) .jl script used to automatically generate the notebooks? It is here:

https://github.com/alan-turing-institute/DataScienceTutorials.jl/blob/master/_literate/EX-GLM.jl

**Comment by drcxcruz** [comment]
I will try it.  thanks

**Comment by drcxcruz** [comment]
hi there,

I did the **DEV** PR  https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/141

Please let us know of any comments.

Thanks

**Comment by ablaom** [comment]
FYI I changed your base to "master". It seems DataScienceTutorials does not use the "dev" branch git workflow like the MLJ* repos. 😳
