### ISSUE TITLE
In learning networks 2 - don't display entire test prediction; 3 or 4 rows should suffice

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#128]
- We display too much at In https://alan-turing-institute.github.io/DataScienceTutorials.jl/getting-started/learning-networks-2/ we have 

![Screen Shot 2020-07-18 at 7 46 56 AM](https://user-images.githubusercontent.com/30517088/87825361-1a193f80-c8cb-11ea-846e-58aa8d783d2e.png)

We could replace `test` with `test[1:4]`, say.

- Also, this is confusing. We just defined a learning network machine - why don't we fit that instead? For comparison, see this part of the manual:

![Screen Shot 2020-07-18 at 7 53 45 AM](https://user-images.githubusercontent.com/30517088/87826082-6022d300-c8cc-11ea-8038-ea1065216256.png)

- And I'm not sure why we define a completely new network in this tutorial. Perhaps there would be better continuity to just use the one from the previous tutorial?

**Comment by tlienart** [comment]
done
