### ISSUE TITLE
Keeping tutorials and their environments together

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#139]
It may be me, but I find it kind of a pain to separately download the environment files for a tutorial. There is also the danger of the user using the wrong environment. Perhaps the user could download a zipped *folder* including the project files. And each tutorial begins with the environment instantiation code (`using Pkg; Pkg.activate(@__DIR__)`) to save the user from remembering/learning how to do this. 

And, of course ultimately we may want each tutorial to have its own environment to make incremental updates possible, and reduce the need for user to install so many packages every time. But Franklin does not support this yet.

**Comment by tlienart** [comment]
Right so the hope was that we'd move on to a system where the user would/could get the right env with a single line of code which would get the right files, instantiate etc. 

I haven't had the occasion to look into this but quant econ does this (afaik) and so we should be able to adapt/copy this

**Comment by ablaom** [comment]
Looks like InstantiateFromUrl.jl is going to be helpful: https://live.juliacon.org/talk/87JCMX

**Comment by tlienart** [comment]
all done
