### ISSUE TITLE
Move this repo to the `JuliaAI` organization?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaAI/DataScienceTutorials.jl#157]
@tlienart @ablaom How would you feel about moving this repo to the `JuliaAI` organization? I know that the tutorials here aren't only for MLJ, but it does seem like a lot of the tutorials are for MLJ, so I was thinking it might help for discoverability for these tutorials to live in the `JuliaAI` organization?

**Comment by tlienart** [comment]
I'm happy to do this, could someone run me through the steps? and then I can do a final push to finish the work to projectify each tutorials (which is long overdue) and do this as well

**Comment by DilumAluthge** [comment]
Here's how you transfer the repo: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-organization

Is this package registered? If not, there are no additional steps.

**Comment by ablaom** [comment]
You may want to update the deployment url for the website.

**Comment by tlienart** [comment]
@ablaom this can be done with redirects so after moving stuff, I'd push a bunch of redirect pages here so that if people click on links they'd get redirected to the new address.

Steps:

1. finish the projectification
2. create a repo at JuliaAI with everything, check development works fine, have Anthony review
3. mark the present repo as archived and replace the content on the gh-pages branch so that it's only a bunch of redirect pages

**Comment by ablaom** [comment]
So by cloning instead of transferring, we can do a better job of link forwarding?

**Comment by DilumAluthge** [comment]
I would actually recommend this instead:
1. Transfer the repo to JuliaAI. This will break GitHub Pages links.
2. Create a new repo at the old `alan-turing-institute` location, and in this repo, create a `gh-pages` branch that simply redirects to the JuliaAI GitHub Pages URL.

**Comment by tlienart** [comment]
I tried (1) today, but I don't have the right to create new repos on JuliaAI

**Comment by ablaom** [comment]
Right. You should now have privileges.

**Comment by tlienart** [comment]
Done and working as far as I can see
