### ISSUE TITLE
Pkg.update in scripts??

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#161]
@tlienart 

Thanks again for all the recent hard work.

In the stacking script I'm looking at I see

```julia
using Pkg # hideall
Pkg.activate("_literate/A-stacking/Project.toml")
Pkg.update()
```

My understanding was that we include the `Project.toml` and `Manifest.toml` to ensure reproducibility. But doing an `update` generally changes the package versions (mutates the Manifest.toml). Instead we should have `Pkg.instantiate()`. 

So long as the user is using the same versions of julia that the toml files were generated with, we should not have any problems, as I see it. 

BTW, this means each script should probably state the julia version being used. If they want to use a different version, then they can proceed at their own risk with `instantiate - p` or `update` or whatever.

Am I missing something here?

**Comment by tlienart** [comment]
My reasoning was that `update` would get the latest set of packages that respect the Project.toml for that tutorial. This is internal though, the user would then be able to do the `instantiate` on their side. The advantage of this is that you don't end up with stale versions everywhere (which was a nightmare when doing the migration) or you have to explicitly put bounds on the Project.toml.

On the user front they should do the instantiate as you say though, note that the block of code you point to is not exposed to the user. However they could download the Project.toml and Manifest.toml and instantiate the environment. I intend to re-enable the link at the top of tutorials where users could download a notebook/script version of the tutorial + the Project and Manifest file, this was done before but now needs to be done a bit differently. See #158. There will be an automatically added block of code at the top that will do exactly what you say (instantiate).

I hope this makes more sense now

**Comment by tlienart** [comment]
I've added the links, generated scripts etc, maybe have a look and let me know if you think that's clear/good enough?

**Comment by ablaom** [comment]
Ok, now I understand. Thanks for clarifying!
