### ISSUE TITLE
Error opening tutorial notebook

### ISSUE THREAD

**Issue by sbacelar** [JuliaAI/DataScienceTutorials.jl#168]
When I try to open Jupyter notebook for the loading tutorial (D0) I get the following error:

`Unreadable Notebook: C:\Users\sbac\Dropbox\JULIA\datasciencetutorials1\tutorial.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')`

**Comment by tlienart** [comment]
ah I should have tried this, there's a `print` missing. thanks will fix

**Comment by tlienart** [comment]
alright this should be fixed, could you try again (maybe after refreshing your browser so that you don't get a stale version) and let me know if it all works for you?

thanks!

**Comment by sbacelar** [comment]
Yes, now it works, thanks.
But I have 2 notes:
1. In "Using CSV" I have to create a new cell called `fpath=joinpath("data", "foo.csv")` and also create the ` foo.csv` file in a new folder called `data`. Right?
2. Examples 2 and 3 refer to external datasets `the contents of which we saved at fpath`. Shall the user do that?

**Comment by tlienart** [comment]
@sbacelar yep I fixed this (in theory the user had to do it but it wasn't very clear so I added the raw stuff)

**Comment by tlienart** [comment]
as per here: https://juliaai.github.io/DataScienceTutorials.jl/data/loading/#basic_usage 

(I'll close this issue but please let me know if you see other problems etc and thanks!)
