### ISSUE TITLE
github.io webpage invalid

### ISSUE THREAD

**Issue by liupgd** [JuliaAI/DataScienceTutorials.jl#176]
I found the tutorial page(https://juliaai.github.io/DataScienceTutorials.jl/) is invalid for several days. Could you please deploy the webpage again? Thanks.

**Comment by tlienart** [comment]
it's back online, that was due to the process of updating to MLJ 0.17, thanks for reporting. Note that there may be some mistakes for a short while on some of the pages while we review changes.
