### ISSUE TITLE
Fixing GLM tutorial

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/DataScienceTutorials.jl#177]
The GLM tutorial doesn't work anymore (and so I've disabled it), something to do with this:

```

X = copy(dfX1)
y = copy(dfY1)

coerce!(X, autotype(X, :string_to_multiclass))
yv = Vector(y[:, 1])

LinearRegressorPipe = @pipeline(Standardizer(),
                                OneHotEncoder(drop_last = true),
                                LinearRegressor())

LinearModel = machine(LinearRegressorPipe, X, yv)
fit!(LinearModel)
fp = fitted_params(LinearModel)
```

Error is something like

```
no method matching keys(::DataFrame)
```

to debug this, please go to https://github.com/JuliaAI/DataScienceTutorials.jl/tree/master/_literate/EX-GLM ; if you figure out how to fix that file, I can do the rest. thanks

cc @ablaom @OkonSamuel

**Comment by OkonSamuel** [comment]
@tlienart thanks for the heads up.
I have traced down the bug to [MLJGLMInterface.jl](https://github.com/JuliaAI/MLJGLMInterface.jl/blob/master/src/MLJGLMInterface.jl#L158).

**Comment by tlienart** [comment]
I'll re-open this since I still need to re-instate it and redeploy
