### ISSUE TITLE
Proposal to redesign the landing page

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#183]
I find the landing page for Data Science Tutorials extremely busy. The current organization around the four basic categories in the right hand menu ("Data Basics", "Getting Started", and so forth) is fine, but I'd like the landing page to be more focused on this question: "I'm this kind of user - so where do I start?". Maybe something like https://alan-turing-institute.github.io/MLJ.jl/dev/learning_mlj/ but even more compact (and prettier 🎨 ). 

Thoughts anyone?

**Comment by ablaom** [comment]
> Some stuff that would be useful to know for the redesign is primarily how the navigation should be shown: keep as is (bar on the side, something similar on small screens) or something else. Having an example website with a good and simple navigation that works well is useful in this regards.

I'm not an expert on this kind of thing, but instead of a menu with every tutorial on it, how about just the groupings ("Getting Started", "End-to-end", and so forth) in a horizontal menu at the top. Then a drop-down menu for each grouping to list the individual tutorials. 

Once your on a tutorial, you don't want any clutter, just a way to get back home (or, ideally, to the next/previous tutorial in sequence).

**Comment by tlienart** [comment]
Navbar are surprisingly hard to get right. Does this https://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=dropdowns-within-navbar kind of match what you had in mind though? (click on show output and change the window size to different representations)

**Comment by ablaom** [comment]
Yeah, that's what I have in mind. But if the variable number of tutorials in each category is an issue for maintenance, it may be better to just open new pages with lists of tutorials. This might be better anyway, as we could provide more details for each tutorial, like we have at the bottom of the current landing page. What do you think?

**Comment by tlienart** [comment]
that makes sense to me, so you'd have a nav with a few "topics" buttons, each of them redirecting to a "topic-index" page with explanations and possibly an additional navbar on the side to help navigation within the topic?

I'll be back with my main computer in a few days, will try to set something up to that effect

**Comment by ablaom** [comment]
Yes. But, I'd prefer not to have side bar in an actual tutorial - the topic-nav bar header would be enough.

Conceptually the changes introduce a new topics layer to the site with existing content of the the landing page distributed out to that layer. The landing page is to be very minimal and to focus on quick re-direction to the appropriate topics layer. I'd be happy to sketch proposed content for this if you'd like.

**Comment by tlienart** [comment]
Sketches are useful! Thanks Anthony :)

**Comment by ablaom** [comment]
Okay, finally got around to this: https://github.com/ablaom/DSTSkeleton

**Comment by ablaom** [comment]
🙏🏾

**Comment by ablaom** [comment]
cc @EssamWisam

**Comment by ablaom** [comment]
Closed as complete.
