### ISSUE TITLE
Plot function debrief

### ISSUE THREAD

**Issue by VishwarathTaduru** [JuliaAI/DataScienceTutorials.jl#188]
I want to unpack the following piece of code to understand better:

figure(figsize=(8,6))
plot(X.LStat, y, ls="none", marker="o")
Xnew = (LStat = collect(range(extrema(X.LStat)..., length=100)),)
plot(Xnew.LStat, MLJ.predict(mach_uni, Xnew))

**Comment by ablaom** [comment]
Could you point to the tutorial in which you found this. Not sure which plotting package you may be using. 

Regarding  this line

```
Xnew = (LStat = collect(range(extrema(X.LStat)..., length=100)),)
```

`extrema` returns a tuple of values `(xmin, xmax)` and the [splat syntax](https://docs.julialang.org/en/v1/manual/faq/#The-two-uses-of-the-...-operator:-slurping-and-splatting) `...` means call `range` as in `range(xmin, xmax, length=100)`, which creates an iteratable object with 1000 evenly spread numbers between `xmin` and `xmax`. I guess the plotting function is not happy with the iterable, so you have `collect` it, i.e., run the iteration to get an ordinary vector.

**Comment by VishwarathTaduru** [comment]
Hi Dr.Blaom,

I found this in the lab3 tutorial on Data Science Tutorials<https://juliaai.github.io/DataScienceTutorials.jl/isl/lab-3/> page

Vishwarath Taduru
President, Manufacturing and Operations club,
PGP Class of 2023
Indian School of Business
M: +91 6281924173| LinkedIn<http://www.linkedin.com/in/vishwarath> | W: www.isb.edu<http://www.isb.edu/>

[A picture containing drawing  Description automatically generated]<https://www.facebook.com/isbedu>
[A picture containing drawing  Description automatically generated]<http://www.linkedin.com/company/indian-School-of-business>
[A picture containing drawing  Description automatically generated]<https://www.youtube.com/user/isbindia>
[A picture containing wheel  Description automatically generated]<https://twitter.com/isbedu>
***@***.***<https://www.instagram.com/isbindia/>

**Comment by ablaom** [comment]
Okay, that's [PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl) which tries to mimic the python matplotlib syntax. So you may want to refer to the matplotlib documentation for clues if you've no luck at the PyPlot.jl page. 

As in most plotting functions, the first argument will be the x-values and the second the y-values. `marker` is how the plotted points appear. I dunno what `ls` means. legend maybe?

**Comment by tlienart** [comment]
`ls` is for `linestyle`
