### ISSUE TITLE
Move learning network stuff into new category?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#194]
After revisiting this site after a long time, I find it disturbing that the learning network stuff (everything after and including "Composing Models")  lives in the "Getting Started" section, as it is *way too advanced* and likely putting new users off. 

Perhaps we need an Advanced section.

Thoughts?

cc @EssamWisam

**Comment by EssamWisam** [comment]
Indeed, I find it overwhelming for new users. Expect a PR that adds a new "Advanced" category to the navigation bar somewhat soon.

**Comment by EssamWisam** [comment]
Closed thanks to #210
