### ISSUE TITLE
Add section "MLJ-goodies"

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/DataScienceTutorials.jl#20]
Could be nice to add a more advanced section where we discuss more specifically some of the things that can be done with MLJ that might not  be straightforward otherwise and are not showcased elsewhere e.g.:

* [ ] testing multiple measures at the same time
* [ ] no retraining if unnecesssary
* [ ] more model composition stuff

@ablaom thoughts on other things we should add?

**Comment by ablaom** [comment]
closing as stale
