### ISSUE TITLE
Many tutorial names are not "informative"

### ISSUE THREAD

**Issue by EssamWisam** [JuliaAI/DataScienceTutorials.jl#221]
One has to click and view the tutorial to know what it is about. The same could be argued about the end-to-end tutorials as well as ensembles (1), (2) and (3).

**Comment by ablaom** [comment]
Just a short note that we will also need to update [this page](https://juliaai.github.io/DataScienceTutorials.jl/info/isl/).

**Comment by EssamWisam** [comment]
Will self-assign to soon update names for all tutorials

**Comment by EssamWisam** [comment]
Time to close.
