### ISSUE TITLE
Problem with deployment

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#236]
I've just made some changes but having trouble deploying. 

I think the problem is related to some recent folder restructuring. Something like `ISL-lab-4` now lives under `isl`.

```julia
> julia deploy.jl
  Activating project at `~/.julia/environments/work`
Current working directory: DataScienceTutorials
  Activating project at `~/GoogleDrive/Julia/MLJ/DataScienceTutorials`
ERROR: LoadError: IOError: open("_literate/ISL-lab-4/.CondaPkg/Project.toml", 0, 0): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:100 [inlined]
 [2] open(path::String, flags::UInt16, mode::Int64)
   @ Base.Filesystem ./filesystem.jl:121
 [3] open
   @ ./filesystem.jl:113 [inlined]
 [4] sendfile(src::String, dst::String)
   @ Base.Filesystem ./file.jl:998
 [5] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
   @ Base.Filesystem ./file.jl:386
 [6] top-level scope
   @ ~/GoogleDrive/Julia/MLJ/DataScienceTutorials/deploy.jl:90
in expression starting at /Users/anthony/GoogleDrive/Julia/MLJ/DataScienceTutorials/deploy.jl:80
```[

**Comment by EssamWisam** [comment]
Unexpected. Quite sure I deployed after changing folder structure to ensure everything is alright (and back then something broke and I fixed it). I may be afraid that this is mixing ignored files with available ones or something on your machine. 

I think what we can do:
- [ ] I to try to deploy again and see if I run  into this (and fix if I do)
- [ ] Ask you to try to deploy again (using a fresh clone if necessary)

**Comment by EssamWisam** [comment]
@ablaom I couldn't reproduce by recloning the repo and attempting deploy. `deploy.jl` produced no such error. You can delete the repo and reclone or try `cleanpull()` as in the bottom of the README to regenerate the site from scratch.

**Comment by EssamWisam** [comment]
That said, deployment still fails due to:
<img width="1326" alt="image" src="https://github.com/JuliaAI/DataScienceTutorials.jl/assets/49572294/80237536-15f6-4ebf-a125-ec469e08759d">

This password issue was something I encountered and spent time with few months ago and the answer was to replace the auth token because the previous one was expired. I'm surprised that has come up again. JuliaAI has not changed in any significant way revently, right @ablaom?

**Comment by ablaom** [comment]
I tried `cleanpull` and still got the same error.

**Comment by ablaom** [comment]
Okay, after recloning I had success from the local end but encountered the same "password" issue as you in the github action.

**Comment by ablaom** [comment]
Updated the deploy GH action, added new public and private keys (one was missing). This seems to have resolved the issue.

**Comment by EssamWisam** [comment]
Thank you. Have no idea how it had worked previously with one key; I followed the pattern I saw somewhere else back then.

**Comment by ablaom** [comment]
> Thank you. Have no idea how it had worked previously with one key; 

Yeah. Totally weird.
