### ISSUE TITLE
New "Contribute" nav-bar item -> 404 Error

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/DataScienceTutorials.jl#237]
It looks like the url for the github pages gets prepended to the desired path that I added (see below). Is this not the way to specify an absolute url?

https://github.com/JuliaAI/DataScienceTutorials.jl/blob/80bd90bae3b729b5982c1b284acfbef96f206727/_layout/head.html#L42

**Comment by EssamWisam** [comment]
I made a PR that attempts to fix that. I believe yes, it is the way but there is logic elsewhere in the site that changes this by appending Github's domain when the site is in deployment (you are viewing a client version). In particular, such logic is necessary for any internal link but not external links.

**Comment by ablaom** [comment]
Okay, now the nav bar completely disappeared. And the "next tutorial buttons" have not effect.
![Screen Shot 2024-06-25 at 8 14 50 AM](https://github.com/JuliaAI/DataScienceTutorials.jl/assets/30517088/409e5c86-99c8-4858-9b83-8a0e24a319db)

I'm going to have to revert the changes for now, as this has effectively killed the site.

**Comment by EssamWisam** [comment]
Oh my goodness. Sorry it was not possible to test since the logic runs if the site is hosted. I have noticed now that the function name is `startsWith` and not `startWith` as I had. No idea why no squiggly lines showed up for me.

**Comment by ablaom** [comment]
Okay, I'll try that, thank you.

**Comment by ablaom** [comment]
Sorted. Thanks for the prompt investigation @EssamWisam 🙏🏾
