### ISSUE TITLE
Title could be more descriptive and SEO-friendly

### ISSUE THREAD

**Issue by ym-han** [JuliaAI/DataScienceTutorials.jl#42]
The current title for the site, "MLJ Tutorials", could be more descriptive: it makes complete sense if you know what MLJ is, but not if you don't. 

The title also doesn't make it clear enough to, e.g., someone googling for an introduction to data analysis or ML in Julia, that the site is, or will be, actually a great first place to start. It doesn't make it clear enough that the tutorials discuss, not only MLJ, but also other data/ML-related packages in the Julia ecosystem.

Off-the-cuff suggestions for alternative titles:

- Data Analysis and Machine Learning in Julia
- Julia for Data Science: An Introduction
- Julia for Data Science: Tutorials and Examples
- Analyzing Data with Julia: A User's Guide

**Comment by tlienart** [comment]
I like the  first suggestion  most  @ablaom what are your thoughts on this?

**Comment by ablaom** [comment]
@ym-han You make a very good point. 

I also like the first suggestion first. 

However, such a change might step on some toes. Personally, I am frequently annoyed by all the "Machine learning in Julia" blogs, workshops, and so forth, which are really only about data wrangling, exploratory data analysis and (maybe) deep learning. 

In the best case scenario, the site actually becomes what the new title presumes, pointing to most of the important ML tools available to the Julia user. We might address my concern with a subtitle - something like:

# Data Analysis and Machine Learning in Julia

### Tutorials with a focus on the MLJ toolbox and ecosystem

(The actual repo title would not change, though, right?)

Thoughts?

**Comment by ym-han** [comment]
Yes, I like the subtitle; I was thinking there should be some mention of MLJ in a subtitle as well. And thanks for pointing out that a title with too expansive an ambit might step on toes -- that's a great point!

**Comment by tlienart** [comment]
Ok great, I'll enact the changes soon

**Comment by ablaom** [comment]
Suggest we drop or replace MLJ logo as well.

**Comment by ablaom** [comment]
Closed as addressed long ago.
