### ISSUE TITLE
General clean up

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/DataScienceTutorials.jl#63]
* [x] use urldownload where possible
* [x] put data in DataScienceTutorialsData
* [ ] use random subset of tutorials for checks
* [x] add the GLM tutorial (data is already up)
* [ ] add a "edit me" button like on the Julia website
* [x] change title of website
* [ ] add explanation of StableRNG, it doesn't really matter here though
* [ ] update DataFrame tutorial which  uses deprecated stuff. 

### External

* [x] update links to MLJTutorials

**Comment by tlienart** [comment]
Use

```julia
using UrlDownload
using DataFrames
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

df = urldownload(url, true, format=:CSV) |> DataFrame 
```

**Comment by ablaom** [comment]
I think the items here are mostly done or stale. So closing.
