### ISSUE TITLE
Instantiate from URL

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/DataScienceTutorials.jl#77]
As kindly indicated on another issue, there's https://github.com/QuantEcon/InstantiateFromURL.jl which helps to instantiate an environment easily, this could help new users greatly.

**Comment by ablaom** [comment]
I think this is fantastic idea. 

I did play around with this at some point and there were some issues, that I can't recall now, sorry. It's more than 3 years since there has been action at that repo, so maybe we put this on ice for now.
