### ISSUE TITLE
Ensembles (3) - Learning networks

### ISSUE THREAD

**Issue by ghost** [JuliaAI/DataScienceTutorials.jl#83]
The Ensembles (3) tuto makes use of learning networks, which are only introduced in the following tutorial (Learning networks). Wouldn't it make sense to move Ensembles (3) after the two tutos on learning networks and have it as an example of how to use learning networks as part of an ensemble?

**Comment by tlienart** [comment]
@gd1989 I think (not now but maybe in a month or so) we should discuss the full structure of the site, possibly  at the same time I finally port the bookdown theme which will look much nicer; at that point it will be useful to  have a detailed plan from you of what tutorials you would put where (as a user) and what tutorials would be good to add where to  give a more complete tour of Julia DS etc

**Comment by ablaom** [comment]
Now moved to a new "advanced" section
